$(document).ready(function(){$("#valima1").click(function(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("valima").style.display="block";history.pushState({},"valima","valima")});$("#kandidaadid1").click(function(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("kandidaadid").style.display="block";history.pushState({},
"kandidaadid","kandidaadid")});$("#avaleht1").click(function(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("pealeht").style.display="block"});$("#tulemused1").click(function(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("tulemused").style.display="block";history.pushState({},"tulemused","tulemused")});
$("#kandideerijale1").click(function(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("kandideerima").style.display="block";history.pushState({},"","kandideerima")})});
function valimaSisenen(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("valijaTuvastus").style.display="block";window.location.hash="valijaTuvastus"}function valimaEdasi(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("valijaKinnitus").style.display="block"}
function valimaKatkestan(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("valijaTuvastus").style.display="block"}function valimaKinnitan(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("valijaT2namine").style.display="block"}
function kandideerijaSisenen(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("kandideerijaTuvastatud").style.display="block"}function lisaKandidatuur(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("kandideeri").style.display="block"}
function kandideeriEdasi(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("kandideerijaKinnitatud").style.display="block"}function kandideeriKatkestan(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("kandideerijaTuvastatud").style.display="block"}
function haaleta(){if("Vali Kandidaat"==document.haaletajaValik.kandidaadiNimi.value)alert("Vali kandidaat");else{$.post("Haaleta",$("#kandidaadiNimi").serialize());$.post("UuendaKandidaadid");for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("valijaT2namine").style.display="block"}}
function valideeriAnkeet(){var b=new Boolean;"piirkond"==document.kandidaadiAnkeet.Piirkond.value?(kandidaadiAnkeet.Piirkond.className="ankeetVigane",document.getElementById("piirkondValitud").innerHTML="",document.getElementById("piirkondPuudu").innerHTML="&#x2717; Valige piirkond",b=!0):(kandidaadiAnkeet.Piirkond.className="ankeetKorras",document.getElementById("piirkondValitud").innerHTML="&#x2713;",document.getElementById("piirkondPuudu").innerHTML="");"kuuluvus"==document.kandidaadiAnkeet.Erakond.value?
(kandidaadiAnkeet.Erakond.className="ankeetVigane",document.getElementById("erakondValitud").innerHTML="",document.getElementById("erakondPuudu").innerHTML="&#x2717; Valige erakond",b=!0):(kandidaadiAnkeet.Erakond.className="ankeetKorras",document.getElementById("erakondValitud").innerHTML="&#x2713;",document.getElementById("erakondPuudu").innerHTML="");document.forms.kandidaadiAnkeet.meil.value.match(/(\d{4})-(\d{2})-(\d{2})/)?(kandidaadiAnkeet.meil.className="ankeetKorras",document.getElementById("emailKorras").innerHTML=
"&#x2713;",document.getElementById("emailPuudu").innerHTML=""):(kandidaadiAnkeet.meil.className="ankeetVigane",document.getElementById("emailKorras").innerHTML="",document.getElementById("emailPuudu").innerHTML="&#x2717; Sisestage s\u00fcnniaeg",b=!0);3>document.kandidaadiAnkeet.telefon.value.length?(kandidaadiAnkeet.telefon.className="ankeetVigane",document.getElementById("telefonKorras").innerHTML="",document.getElementById("telefonPuudu").innerHTML="&#x2717; Sisestage amet",b=!0):(kandidaadiAnkeet.telefon.className=
"ankeetKorras",document.getElementById("telefonKorras").innerHTML="&#x2713;",document.getElementById("telefonPuudu").innerHTML="");3>document.kandidaadiAnkeet.nimi.value.length?(kandidaadiAnkeet.nimi.className="ankeetVigane",document.getElementById("nimiKorras").innerHTML="",document.getElementById("nimiPuudu").innerHTML="&#x2717; Sisestage nimi",b=!0):(kandidaadiAnkeet.nimi.className="ankeetKorras",document.getElementById("nimiKorras").innerHTML="&#x2713;",document.getElementById("nimiPuudu").innerHTML=
"");if(!0===b)return!1;$.post("LisaKandidaat",$("#ankeediVorm").serialize());$.post("UuendaKandidaadid");for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("kandideerijaKinnitatud").style.display="block"}$(function(){$("#kandidaadiOtsing").autocomplete({source:"PakuKandidaat",minLength:2})});
function vajutanOtsi(){$("#tabel tr:gt(0)").remove();$.getJSON("Otsing",$("#kandidaadiOtsinguVorm").serialize(),function(b){$.each(b.Kandidaadid,function(){var a="<tr><td>"+this.nimi+"</td><td>"+this.vanus+"</td><td>"+this.erakond+"</td><td>"+this.amet+"</td><td>"+this.piirkond+'</td><td><a href="img/kandidaat.png"><img class="thumbnail_photo" src="img/kandidaat.png" alt="kandidaat1"></a></td></tr>';$("#tabel").append(a)})})}
function peidanOtsi(){for(var b=document.getElementById("sisu").getElementsByClassName("sisu_a"),a=0;a<b.length;a++)b[a].style.display="none";document.getElementById("kandidaadid").style.display="block"}
$.ajax({type:"GET",url:"/Nimekiri",dataType:"json",success:function(b){window.sessionStorage&&window.localStorage.setItem("nimekiri",JSON.stringify(b));$.each(b.Kandidaadid,function(){var a="<tr><td>"+this.nimi+"</td><td>"+this.vanus+"</td><td>"+this.erakond+"</td><td>"+this.amet+"</td><td>"+this.piirkond+'</td><td><a href="img/kandidaat.png"><img class="thumbnail_photo" src="img/kandidaat.png" alt="kandidaat1"></a></td></tr>';$("#tabel").append(a)})},error:function(){var b=jQuery.parseJSON(window.localStorage.getItem("nimekiri"));
$.each(b.Kandidaadid,function(){var a="<tr><td>"+this.nimi+"</td><td>"+this.vanus+"</td><td>"+this.erakond+"</td><td>"+this.amet+"</td><td>"+this.piirkond+'</td><td><a href="img/kandidaat.png"><img class="thumbnail_photo" src="img/kandidaat.png" alt="kandidaat1"></a></td></tr>';$("#tabel").append(a)})}});
$.ajax({type:"GET",url:"/PiirkonnadeSt",dataType:"json",success:function(b){window.sessionStorage&&window.localStorage.setItem("piirkonnad",JSON.stringify(b));$.each(b.Haaled,function(){var a="<tr><td>"+this.kedamida+"</td><td>"+this.hulk+"</td><td>"+this.protsent+"</td></tr>";$("#tabelpiirk").append(a)})},error:function(){var b=jQuery.parseJSON(window.localStorage.getItem("piirkonnad"));$.each(b.Haaled,function(){var a="<tr><td>"+this.kedamida+"</td><td>"+this.hulk+"</td><td>"+this.protsent+"</td></tr>";
$("#tabelpiirk").append(a)})}});
$.ajax({type:"GET",url:"/ErakonnadeSt",dataType:"json",success:function(b){window.sessionStorage&&window.localStorage.setItem("erakonnad",JSON.stringify(b));$.each(b.Haaled,function(){var a="<tr><td>"+this.kedamida+"</td><td>"+this.hulk+"</td><td>"+this.protsent+"</td></tr>";$("#tabelerakond").append(a)})},error:function(){var b=jQuery.parseJSON(window.localStorage.getItem("erakonnad"));$.each(b.Haaled,function(){var a="<tr><td>"+this.kedamida+"</td><td>"+this.hulk+"</td><td>"+this.protsent+"</td></tr>";
$("#tabelerakond").append(a)})}});
$.ajax({type:"GET",url:"/KandidaadiSt",dataType:"json",success:function(b){window.sessionStorage&&window.localStorage.setItem("kandidaadid",JSON.stringify(b));$.each(b.Haaled,function(){var a="<tr><td>"+this.kedamida+"</td><td>"+this.hulk+"</td><td>"+this.protsent+"</td></tr>";$("#tabelknd").append(a)})},error:function(){var b=jQuery.parseJSON(window.localStorage.getItem("kandidaadid"));$.each(b.Haaled,function(){var a="<tr><td>"+this.kedamida+"</td><td>"+this.hulk+"</td><td>"+this.protsent+"</td></tr>";
$("#tabelknd").append(a)})}});
$.ajax({type:"GET",url:"/RiigiSt",dataType:"json",success:function(b){window.sessionStorage&&window.localStorage.setItem("riik",JSON.stringify(b));$.each(b.Haaled,function(){var a="<tr><td>"+this.kedamida+"</td><td>"+this.hulk+"</td><td>"+this.protsent+"</td></tr>";$("#tabelrg").append(a)})},error:function(){var b=jQuery.parseJSON(window.localStorage.getItem("riik"));$.each(b.Haaled,function(){var a="<tr><td>"+this.kedamida+"</td><td>"+this.hulk+"</td><td>"+this.protsent+"</td></tr>";$("#tabelrg").append(a)})}});
function parteideKaupa(){document.getElementById("erakonnaTabel").style.display="block";document.getElementById("koguRiigiTabel").style.display="none";document.getElementById("kandidaatideTabel").style.display="none";document.getElementById("piirkonnaTabel").style.display="none";window.location.hash="tulemusedParteid"}
function piirkondadeKaupa(){document.getElementById("erakonnaTabel").style.display="none";document.getElementById("koguRiigiTabel").style.display="none";document.getElementById("kandidaatideTabel").style.display="none";document.getElementById("piirkonnaTabel").style.display="block";window.location.hash="tulemusedPiirkonnad"}
function kandidaatideKaupa(){document.getElementById("erakonnaTabel").style.display="none";document.getElementById("piirkonnaTabel").style.display="none";document.getElementById("koguRiigiTabel").style.display="none";document.getElementById("kandidaatideTabel").style.display="block";window.location.hash="tulemusedKandidaadid"}
function koguRiik(){document.getElementById("erakonnaTabel").style.display="none";document.getElementById("piirkonnaTabel").style.display="none";document.getElementById("koguRiigiTabel").style.display="block";document.getElementById("kandidaatideTabel").style.display="none";window.location.hash="tulemusedRiik"}function tyhistaHaal(){$.post("TyhistaHaal");$.post("UuendaKandidaadid");alert("H\u00e4\u00e4l t\u00fchistatud")}
function initialize(){var b=new google.maps.LatLng(59.9,21.5),a=new google.maps.LatLng(58.36611,26.73611),w=new google.maps.LatLng(59.32389,24.83806),x=new google.maps.LatLng(58,26.14528),v=new google.maps.LatLng(58.89778,22.64917),O=new google.maps.LatLng(59.19972,27.35472),P=new google.maps.LatLng(58.74667,26.39389),Q=new google.maps.LatLng(58.94306,23.64139),R=new google.maps.LatLng(59.14639,26.35556),S=new google.maps.LatLng(58.06028,27.06917),T=new google.maps.LatLng(58.47472,24.71083),U=new google.maps.LatLng(58.90722,
24.79278),V=new google.maps.LatLng(58.34806,22.50389),W=new google.maps.LatLng(58.36389,25.59),X=new google.maps.LatLng(57.73389,27.01917),Y=new google.maps.LatLng(58.88556,25.55722),b={center:b,zoom:7,disableDefaultUI:!0,mapTypeId:google.maps.MapTypeId.ROADMAP},c=new google.maps.Map(document.getElementById("Kaart"),b);google.maps.event.trigger(c,"resize");var e=new google.maps.Marker({position:a});e.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var f=new google.maps.Marker({position:w});
f.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var g=new google.maps.Marker({position:x});g.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var h=new google.maps.Marker({position:v});h.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var j=new google.maps.Marker({position:O});j.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var k=new google.maps.Marker({position:P});k.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var l=new google.maps.Marker({position:Q});
l.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var m=new google.maps.Marker({position:R});m.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var n=new google.maps.Marker({position:S});n.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var p=new google.maps.Marker({position:T});p.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var q=new google.maps.Marker({position:U});q.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var r=new google.maps.Marker({position:V});
r.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var s=new google.maps.Marker({position:W});s.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var t=new google.maps.Marker({position:X});t.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");var u=new google.maps.Marker({position:Y});u.setIcon("http://maps.google.com/mapfiles/ms/icons/pink.png");e.setMap(c);f.setMap(c);g.setMap(c);h.setMap(c);j.setMap(c);k.setMap(c);l.setMap(c);m.setMap(c);n.setMap(c);p.setMap(c);
q.setMap(c);r.setMap(c);s.setMap(c);t.setMap(c);u.setMap(c);var y=new google.maps.InfoWindow({content:"Tartumaa piirkond"});google.maps.event.addListener(e,"click",function(){y.open(c,e)});var z=new google.maps.InfoWindow({content:"Harjumaa piirkond"});google.maps.event.addListener(f,"click",function(){z.open(c,f)});var A=new google.maps.InfoWindow({content:"Valgamaa piirkond"});google.maps.event.addListener(g,"click",function(){A.open(c,g)});var B=new google.maps.InfoWindow({content:"Hiiumaa piirkond"});
google.maps.event.addListener(h,"click",function(){B.open(c,h)});var C=new google.maps.InfoWindow({content:"Ida-Virumaa piirkond"});google.maps.event.addListener(j,"click",function(){C.open(c,j)});var D=new google.maps.InfoWindow({content:"J\u00f5gevamaa piirkond"});google.maps.event.addListener(k,"click",function(){D.open(c,k)});var E=new google.maps.InfoWindow({content:"L\u00e4\u00e4nemaa piirkond"});google.maps.event.addListener(l,"click",function(){E.open(c,l)});var F=new google.maps.InfoWindow({content:"L\u00e4\u00e4ne-Virumaa piirkond"});
google.maps.event.addListener(m,"click",function(){F.open(c,m)});var G=new google.maps.InfoWindow({content:"P\u00f5lvamaa piirkond"});google.maps.event.addListener(n,"click",function(){G.open(c,n)});var H=new google.maps.InfoWindow({content:"P\u00e4rnumaa piirkond"});google.maps.event.addListener(p,"click",function(){H.open(c,p)});var I=new google.maps.InfoWindow({content:"Raplamaa piirkond"});google.maps.event.addListener(q,"click",function(){I.open(c,q)});var J=new google.maps.InfoWindow({content:"Saaremaa piirkond"});
google.maps.event.addListener(r,"click",function(){J.open(c,r)});var K=new google.maps.InfoWindow({content:"Viljandimaa piirkond"});google.maps.event.addListener(s,"click",function(){K.open(c,s)});var L=new google.maps.InfoWindow({content:"V\u00f5rumaa piirkond"});google.maps.event.addListener(t,"click",function(){L.open(c,t)});var M=new google.maps.InfoWindow({content:"J\u00e4rvamaa piirkond"});google.maps.event.addListener(u,"click",function(){M.open(c,u)});$.ajax({type:"POST",url:"/PES",dataType:"json",
data:{id:"1"},success:function(d){"Pruun"==d.Haaled[0].kedamida?e.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==d.Haaled[0].kedamida?e.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==d.Haaled[0].kedamida?e.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==d.Haaled[0].kedamida&&e.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var a=y.getContent(),a=a+("<br> Liider: "+d.Haaled[0].kedamida+" Erakond <br>"+d.Haaled[0].protsent+
"%");y.setContent(a)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"2"},success:function(d){"Pruun"==d.Haaled[0].kedamida?g.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==d.Haaled[0].kedamida?g.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==d.Haaled[0].kedamida?g.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==d.Haaled[0].kedamida&&g.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var a=A.getContent(),
a=a+("<br> Liider: "+d.Haaled[0].kedamida+" Erakond <br>"+d.Haaled[0].protsent+"%");A.setContent(a)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"3"},success:function(d){"Pruun"==d.Haaled[0].kedamida?u.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==d.Haaled[0].kedamida?u.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==d.Haaled[0].kedamida?u.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==d.Haaled[0].kedamida&&
u.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var a=M.getContent(),a=a+("<br> Liider: "+d.Haaled[0].kedamida+" Erakond <br>"+d.Haaled[0].protsent+"%");M.setContent(a)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"4"},success:function(d){"Pruun"==d.Haaled[0].kedamida?f.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==d.Haaled[0].kedamida?f.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==d.Haaled[0].kedamida?f.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):
"Sinine"==d.Haaled[0].kedamida&&f.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var a=z.getContent(),a=a+("<br> Liider: "+d.Haaled[0].kedamida+" Erakond <br>"+d.Haaled[0].protsent+"%");z.setContent(a)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"5"},success:function(a){"Pruun"==a.Haaled[0].kedamida?h.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?h.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?
h.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&h.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=B.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");B.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"6"},success:function(a){"Pruun"==a.Haaled[0].kedamida?j.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?j.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):
"Kollane"==a.Haaled[0].kedamida?j.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&j.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=C.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");C.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"7"},success:function(a){"Pruun"==a.Haaled[0].kedamida?k.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==
a.Haaled[0].kedamida?k.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?k.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&k.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=D.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");D.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"8"},success:function(a){"Pruun"==a.Haaled[0].kedamida?
l.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?l.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?l.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&l.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=E.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");E.setContent(b)}});$.ajax({type:"POST",url:"/PES",
dataType:"json",data:{id:"9"},success:function(a){"Pruun"==a.Haaled[0].kedamida?m.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?m.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?m.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&m.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=F.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+
a.Haaled[0].protsent+"%");F.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"10"},success:function(a){"Pruun"==a.Haaled[0].kedamida?n.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?n.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?n.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&n.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");
var b=G.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");G.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"11"},success:function(a){"Pruun"==a.Haaled[0].kedamida?p.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?p.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?p.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==
a.Haaled[0].kedamida&&p.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=H.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");H.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"12"},success:function(a){"Pruun"==a.Haaled[0].kedamida?q.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?q.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?
q.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&q.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=I.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");I.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"13"},success:function(a){"Pruun"==a.Haaled[0].kedamida?r.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?r.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):
"Kollane"==a.Haaled[0].kedamida?r.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&r.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=J.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");J.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"14"},success:function(a){"Pruun"==a.Haaled[0].kedamida?s.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==
a.Haaled[0].kedamida?s.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?s.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&s.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=K.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");K.setContent(b)}});$.ajax({type:"POST",url:"/PES",dataType:"json",data:{id:"15"},success:function(a){"Pruun"==a.Haaled[0].kedamida?
t.setIcon("http://maps.google.com/mapfiles/ms/icons/red.png"):"Roheline"==a.Haaled[0].kedamida?t.setIcon("http://maps.google.com/mapfiles/ms/icons/green.png"):"Kollane"==a.Haaled[0].kedamida?t.setIcon("http://maps.google.com/mapfiles/ms/icons/yellow.png"):"Sinine"==a.Haaled[0].kedamida&&t.setIcon("http://maps.google.com/mapfiles/ms/icons/blue.png");var b=L.getContent(),b=b+("<br> Liider: "+a.Haaled[0].kedamida+" Erakond <br>"+a.Haaled[0].protsent+"%");L.setContent(b)}});c.controls[google.maps.ControlPosition.RIGHT_BOTTOM].push(document.getElementById("legend"));
var a=document.getElementById("legend"),N;for(N in styles)w=N.name,x=N.icon,v=document.createElement("div"),v.innerHTML='<img src="'+x+'"> '+w,a.appendChild(v)};